# Programming Hyperledger Fabric
# Siddharth Jain
# (c) All rights reserved.

# This work is a derivative of https://github.com/hyperledger/blockchain-explorer/blob/master/docker-compose.yaml
# licensed under SPDX-License-Identifier: Apache-2.0
# A complete copy of the license can be found here: https://www.apache.org/licenses/LICENSE-2.0

# there is no need to run any prometheus and grafana containers. see
# https://lists.hyperledger.org/g/explorer/message/99

version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  mynetwork.com:
    external:
      name: pharmanet

services:

  explorerdb.mynetwork.com:
    image: hyperledger/explorer-db:1.1.0
    container_name: explorerdb.mynetwork.com
    hostname: explorerdb.mynetwork.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork.com

  explorer.mynetwork.com:
    image: phf/explorer:latest
    container_name: explorer.mynetwork.com
    hostname: explorer.mynetwork.com
    environment:
      - DATABASE_HOST=explorerdb.mynetwork.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=debug
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./local_fabric.json:/opt/explorer/app/platform/fabric/local_fabric.json
      - "${CRYPTO_DIR}:/tmp/crypto"
      - walletstore:/opt/wallet
    command: sh -c "node /opt/explorer/main.js && tail -f /dev/null"
    ports:
      - 8090:8080
    depends_on:
      explorerdb.mynetwork.com:
        condition: service_healthy
    networks:
      - mynetwork.com

